homework tasks
AlesiaRebkavets/Hometask_Lec4 pull request #1
Opened 2022-10-28 00:52 UTC by AlesiaRebkavets

can't fix errors for task 7 and task 8

2022-10-31 18:18 UTC, ezhukovskaya requested changes

2022-10-31 18:18 UTC, ezhukovskaya commented on Hometask_Lec4/Program.cs
> +            }
отлично, можно было усилить абстракцию
`while(n > 0)
{
	sum += n--
}`

2022-10-31 18:18 UTC, ezhukovskaya commented on Hometask_Lec4/Program.cs
> +        byte[] arr = new byte[5] { 3, 5, 9, 8, 15 };               // initialisation of array
byte[5]
5 - можно не указывать

2022-10-31 18:18 UTC, ezhukovskaya commented on Hometask_Lec4/Program.cs
> +        short m = 1;
почему short

2022-10-31 18:18 UTC, ezhukovskaya commented on Hometask_Lec4/Program.cs
> +            if (arr[i] == "Hello")                                 // determine if 'Hello' was entered
1. можно прямо так написать `if(arr[i].ToLower() == "hello")`. Не нужно создавать лишнюю переменную
2. Надо посмотреть, возоно у тебя не подтянут пакет

2022-10-31 18:18 UTC, ezhukovskaya commented on Hometask_Lec4/Program.cs
> +        // ПОХОЖЕ НА ОШИБКУ КАК В TASK 5, ПОДСКАЖИ, ПОЖАЛУЙСТА, В ЧЕМ ПРИЧИНА
проще посмотреть как у тебя выглядит, у меня код отработал

2022-10-31 18:18 UTC, ezhukovskaya commented on Hometask_Lec4/Program.cs
> +        for (byte i = 0; i > 10; i++)
найди тут ошибку

2022-10-31 18:18 UTC, ezhukovskaya commented on Hometask_Lec4/Program.cs
> +        for (byte k = 0; k < 10; k++)
и тут тоже

2022-11-03 13:14 UTC, AlesiaRebkavets commented on Hometask_Lec4/Program.cs
> +            }
edited task 1

2022-11-03 13:15 UTC, AlesiaRebkavets commented on Hometask_Lec4/Program.cs
> +        byte[] arr = new byte[5] { 3, 5, 9, 8, 15 };               // initialisation of array
deleted

2022-11-03 13:17 UTC, AlesiaRebkavets commented on Hometask_Lec4/Program.cs
> +        short m = 1;
этот тип занимает меньше места в памяти чем остальные + его размерность подходит для значения

2022-11-03 13:18 UTC, AlesiaRebkavets commented on Hometask_Lec4/Program.cs
> +            if (arr[i] == "Hello")                                 // determine if 'Hello' was entered
исправила, работает

2022-11-03 13:22 UTC, AlesiaRebkavets commented on Hometask_Lec4/Program.cs
> +        // ПОХОЖЕ НА ОШИБКУ КАК В TASK 5, ПОДСКАЖИ, ПОЖАЛУЙСТА, В ЧЕМ ПРИЧИНА
исправила, работает
теперь arr[0] элемент массива инициализируется перед циклом for. Его значение присваивается переменным min, max до цикла

2022-11-03 13:23 UTC, AlesiaRebkavets commented on Hometask_Lec4/Program.cs
> +        for (byte i = 0; i > 10; i++)
"i < 10", исправила

2022-11-03 13:23 UTC, AlesiaRebkavets commented on Hometask_Lec4/Program.cs
> +        for (byte k = 0; k < 10; k++)
исправила

2022-11-04 07:25 UTC, ezhukovskaya approved these changes

2022-11-04 08:35 UTC, merged